theforeman/foremanctl

container-images/candlepin/Containerfile, container-images/foreman/Containerfile
We can reduce the amount of disk required and layers for foreman and candlepin images
```
REPOSITORY                TAG         IMAGE ID      CREATED         SIZE
quay.io/ehelms/candlepin  4.4-test    41bbe74d7daa  11 seconds ago  1.3 GB
quay.io/ehelms/candlepin  4.4         cc37b39dce02  18 minutes ago  1.41 GB
```
```
REPOSITORY              TAG            IMAGE ID      CREATED         SIZE
quay.io/ehelms/foreman  nightly-layer  66760eacf2f9  18 minutes ago  459 MB
quay.io/ehelms/foreman  nightly        076654104b2d  31 minutes ago  585 MB
```
Why installing candlepin requires `pipewire-libs` o.O
=> Reduce the amount of layers for Foreman and Candlepin

container-images/foreman-proxy/Containerfile, container-images/foreman-proxy/Makefile, container-images/foreman/Containerfile
Before adding `--nodocs` and `dnf clean all`
```
REPOSITORY              TAG         IMAGE ID      CREATED         SIZE
quay.io/ehelms/foreman  nightly     a20e228905bb  10 seconds ago  884 MB
quay.io/ehelms/foreman-proxy  nightly     2d3a73f1ded9  29 seconds ago  458 MB
```
After `--nodocs`` and `dnf clean all`
```
REPOSITORY              TAG             IMAGE ID      CREATED        SIZE
quay.io/ehelms/foreman  nightly-nodocs  ab9ff2fb57a0  5 seconds ago  774 MB
quay.io/ehelms/foreman-proxy  nightly-nodocs  dfe53a6f8f3c  12 minutes ago  351 MB
```
=> Reduce Container sizes

roles/foreman/tasks/main.yaml
otherwise they don't know which certs to use
=> add settings.yaml to dynflow containers

Vagrantfile, roles/foreman/tasks/main.yaml
- **increase CPUs and memory**
- **start dynflow later**
=> increase CPUs and memory

playbooks/deploy.yaml, roles/httpd/defaults/main.yml, roles/pulp/defaults/main.yaml, roles/pulp/tasks/main.yaml, roles/pulp/templates/settings.py.j2, tests/pulp_test.py
implementation of pulp services(api, content and worker)
=> add pulp services

roles/pulp/templates/settings.py.j2
Based on discussion: https://github.com/theforeman/foreman-quadlet/pull/34#discussion_r1843496880
The `PORT` setting in the database configuration is redundant because Django defaults to the PostgreSQL standard port (`5432`) when the `PORT` setting is omitted.
Reference: https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-PORT
=> Remove PostgreSQL PORT setting

run_tests, tests/candlepin_test.py, tests/conftest.py, tests/foreman_proxy_test.py, tests/foreman_test.py, tests/httpd_test.py, tests/postgresql_test.py, tests/pulp_test.py, tests/redis_test.py
this allows differentiating different types of hosts which we will have soon
=> use a dedicated "server" fixture, instead of the generic "host"

roles/pulp/defaults/main.yaml, roles/pulp/templates/settings.py.j2
Fixes https://github.com/theforeman/foreman-quadlet/issues/58
=> disable pulpcore analytics

.github/workflows/test.yml
This will allow us to see the runtime of the actual deployment of the application.
=> Split setup and deploy steps

roles/certificate_checks/tasks/main.yml
the command doesn't alter the system and executing it allows to see if
the certs are valid w/o risking any changes to the system
=> always run k-c-c, even in check mode

container-images/candlepin/Containerfile
This avoids some graphical libraries that the JRE pulls in.
=> Avoid installing weak dependencies for candlepin

roles/pulp/tasks/main.yaml
When inspecting the journal I noticed warnings:
Unknown key name 'Wants' in section 'Install', ignoring.
The correct section is Unit.
Fixes: fb87fb4a1d0494f964d98fc86cf4d1aafecf0713 ("Change from Pulp all-in-one to split services")
=> Put Wants= in the correct section

.github/workflows/test.yml, ansible.cfg, playbooks/deploy.yaml, playbooks/images.yaml, vars/images.yml
Pre-pulling the images isn't necessary, but can help differentiate the runtime of the actual installer part vs. image pull.
=> Add playbook to pre-pull images

playbooks/deploy.yaml, tests/foreman_api_test.py
I noticed this output in the logs:
```
Mar 11 16:15:41 quadlet.example.com python3[54896]: ansible-ansible.legacy.systemd Invoked with name=postgresql state=restarted daemon_reload=False daemon_reexec=False scope=system no_block=False enabled=None force=None masked=None
Mar 11 16:15:41 quadlet.example.com systemd[1]: Stopping PostgreSQL database server...
Mar 11 16:15:41 quadlet.example.com foreman[51658]: FATAL:  terminating connection due to administrator command
Mar 11 16:15:41 quadlet.example.com foreman[51658]: #<Thread:0x00007f8f301e39a0 /usr/share/gems/gems/logging-2.4.0/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Mar 11 16:15:41 quadlet.example.com foreman[51658]: /usr/share/gems/gems/sequel-5.89.0/lib/sequel/adapters/postgres …
```
=> Set postgres handler to started to prevent restarts

container-images/foreman/Containerfile
This allows reusing the base layers in case you build multiple variations.
Currently untested and submitting for early review. If this is a good idea, we should also apply it to foreman-proxy.
=> Move the plugin specific layers to the bottom

roles/candlepin/tasks/main.yml
This moves the command into systemd/podman which means it can reliably report if the service is actually up.
=> Use health_startup_cmd to determine if Candlepin is up

roles/foreman/tasks/main.yaml
Mirrors configuration from RPM based deployment (https://github.com/theforeman/foreman/blob/develop/extras/systemd/dynflow-sidekiq%40.service#L25-L27) and maybe solves https://github.com/theforeman/foreman-quadlet/issues/112
=> Add restart on failure to dynflow services

playbooks/deploy.yaml, playbooks/setup.yaml, requirements.yml, roles/postgresql/defaults/main.yml, roles/postgresql/tasks/main.yml, tests/postgresql_test.py
This PR transitions the pgsql installation from an RPM-based installation to a containerized based.
=> migrate pgsql installation from rpm to container-based

.github/workflows/test.yml, docs/container-image-builds.md
This may not be the long term place we want to store these documents. In the short term, this feels like the right place.
This a lightweight copying of container build strategy that came out of some in person conversations.
=> Add documentation for container builds

.github/workflows/test.yml, README.md, ansible.cfg, start-vms, stop-vms, vagrant.py
Introduces a script to start and stop VMs and produce a static inventory. This speeds up each call after the fact and creates less reliance on Vagrant.
=> Abstract away Vagrant as the VM provider to speed up subsequent calls

playbooks/deploy.yaml, roles/debug_tools/files/podman-print-secret, roles/debug_tools/tasks/main.yml
This is helpful for debugging as it allows easily printing a secret.
```
print-secret candlepin-candlepin-conf
```
=> Add debug script to easily print secrets

playbooks/deploy.yaml, roles/candlepin/defaults/main.yml, roles/candlepin/templates/candlepin.conf.j2, roles/foreman/defaults/main.yaml, roles/foreman/tasks/main.yaml, roles/pulp/defaults/main.yaml, roles/pulp/tasks/main.yaml, vars/database.yml
This does include SSL variables, but not SSL testing for PostgreSQL access. I think that will require quite a bit extra to spin up a variation of testing that include those. This PR is instead intended to centralize the database variables to a single set of inputs, that I can then use with Obsah (https://github.com/theforeman/obsah/pull/63) to do variable combining and mutual requirement testing on top of https://github.com/theforeman/foreman-quadlet/pull/13.
=> Add all database variables for Foreman, Candlepin and Pulp

src/roles/pulp/tasks/main.yaml, tests/pulp_test.py
This was needed before we had cert auth.
Fixes: 2ad1ca5343aa ("configure cert auth for pulp")
=> Stop setting a fixed password for Pulp admin user

.packit.yml, rop, rop.spec
This builds on https://github.com/theforeman/foreman-quadlet/pull/131 and adds an RPM spec file with packit configuration.
<del>Right now it won't include any of the galaxy modules we depend on and we need to have a discussion on how to resolve that. Will we vendor those into the Python package or list them separate in the RPM spec file?</del>
=> Add RPM spec and packit config

src/roles/foreman/tasks/main.yaml
In my testing I sometimes got an error that dict didn't have a json property. I suspect the service returned an error message so this first checks for status 200.
=> Expect status 200 on ping output too

src/roles/pulp/tasks/main.yaml
This relies on using systemd notification support to signal a service is ready. That means we no longer need to wait for it to be listening and they can start in parallel.
For that we need to wait for the migration to complete, which is important. Otherwise steps after it may run that depend on a migrated database.
Split off from https://github.com/theforeman/foreman-quadlet/pull/114
=> Rely on sdnotify: true for pulp

tests/conftest.py, tests/foreman_api_test.py
this is better than random sleeps
=> always wait for MetadataGenerate when creating repos

setup-environment
This will work better in case there are conflicting requirements.
It also skips creation and activation of the virtual environment if one is already active. Doing so makes it easy to use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/) or other tooling.
=> Install python dependencies in a single run & detect active virtual env

src/roles/check_database_connection/tasks/check.yaml, src/roles/check_database_connection/tasks/main.yaml
Depends on https://github.com/theforeman/foremanctl/pull/210
Extends the existing database connectivity checks to include Candlepin and Pulp when database_mode=external.
=> Add database connectivity checks for Candlepin and Pulp

Vagrantfile
We've been using these in forklift since a while again [1], and they work fine.
[1] https://github.com/theforeman/forklift/commit/dd0cb40c3345b7bff526893e6ebbff9319c2b128
=> Use the Hashicorp cloud again for CentOS boxes

src/playbooks/setup-hammer/setup-hammer.yaml, src/roles/hammer/tasks/main.yml, src/roles/hammer/templates/hammer-root.yml.j2, tests/hammer_test.py
With the current hammer deployment, for each hammer command we need to pass username and password.
in the current deployment we configure the credentials for root so that root does not need to pass username/password with each hammer command.
reference from current-installer(https://github.com/theforeman/puppet-foreman/blob/master/manifests/cli.pp#L72)
=> Configure hammer for root
